#!/usr/bin/env node
/**
 * Claude Notify — One-click installer
 *
 * Usage:  npx claude-notify-setup
 *
 * Sets up Claude Code hooks for mobile notifications.
 * Works on macOS, Linux, and Windows.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');
const { execSync } = require('child_process');
const readline = require('readline');

// ─── Colors ─────────────────────────────────────────────────────────────────
const c = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  green: '\x1b[32m',
  blue: '\x1b[34m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  magenta: '\x1b[35m',
};

function log(msg) { console.log(msg); }
function step(msg) { log(`\n${c.blue}▸${c.reset} ${c.bold}${msg}${c.reset}`); }
function ok(msg) { log(`  ${c.green}✓${c.reset} ${msg}`); }
function warn(msg) { log(`  ${c.yellow}⚠${c.reset} ${msg}`); }
function err(msg) { log(`  ${c.red}✗${c.reset} ${msg}`); }

// ─── Prompt ─────────────────────────────────────────────────────────────────
function ask(question) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
    rl.question(`${c.cyan}?${c.reset} ${question} `, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

// ─── Paths ──────────────────────────────────────────────────────────────────
const HOME = os.homedir();
const CLAUDE_DIR = path.join(HOME, '.claude');
const HOOKS_DIR = path.join(CLAUDE_DIR, 'hooks');
const SETTINGS_PATH = path.join(CLAUDE_DIR, 'settings.json');
const ENV_PATH = path.join(HOOKS_DIR, '.env');
const SERVICE_ACCOUNT_DEST = path.join(HOOKS_DIR, 'serviceAccountKey.json');
const INSTALLER_DIR = __dirname;
const PROJECT_ID = 'claude-notify-41f99';

// ─── Main ───────────────────────────────────────────────────────────────────
async function main() {
  log('');
  log(`${c.bold}${c.magenta}  Claude Notify Installer${c.reset}`);
  log(`${c.dim}  Mobile notifications for Claude Code${c.reset}`);
  log(`${c.dim}  ─────────────────────────────────────${c.reset}`);
  log('');

  // Pre-check: Node.js version
  const nodeVersion = parseInt(process.version.slice(1));
  if (nodeVersion < 18) {
    err(`Node.js 18+ required (you have ${process.version})`);
    process.exit(1);
  }
  ok(`Node.js ${process.version}`);

  // Pre-check: Claude Code installed
  if (!fs.existsSync(CLAUDE_DIR)) {
    err('~/.claude directory not found. Is Claude Code installed?');
    process.exit(1);
  }
  ok('Claude Code detected');

  // ── Step 1: Get UID ──────────────────────────────────────────────────────
  step('Setup');
  log('');
  log(`  ${c.dim}Open the Claude Notify app on your phone, sign in with`);
  log(`  Google, and copy the UID shown on the home screen.${c.reset}`);
  log('');

  const uid = await ask('Paste your Firebase UID:');
  if (!uid || uid.length < 10) {
    err('Invalid UID. Please copy it from the Claude Notify app.');
    process.exit(1);
  }
  ok(`UID: ${uid.slice(0, 8)}...`);

  // ── Step 2: Create hooks directory ────────────────────────────────────────
  step('Installing hooks');

  fs.mkdirSync(HOOKS_DIR, { recursive: true });
  ok('Created ~/.claude/hooks/');

  // ── Step 3: Copy hook files ───────────────────────────────────────────────
  const hookFiles = [
    'bridge.js',
    'stop.js',
    'pre-tool-use.js',
    'post-tool-use.js',
    'notification.js',
  ];

  for (const file of hookFiles) {
    const src = path.join(INSTALLER_DIR, 'hooks', file);
    const dest = path.join(HOOKS_DIR, file);
    if (!fs.existsSync(src)) {
      warn(`${file} not found in installer, skipping`);
      continue;
    }
    fs.copyFileSync(src, dest);
    // Make executable on Unix
    if (process.platform !== 'win32') {
      fs.chmodSync(dest, 0o755);
    }
    ok(file);
  }

  // ── Step 4: Copy service account key ──────────────────────────────────────
  const serviceAccountSrc = path.join(INSTALLER_DIR, 'service-account-key.json');
  if (fs.existsSync(serviceAccountSrc)) {
    fs.copyFileSync(serviceAccountSrc, SERVICE_ACCOUNT_DEST);
    ok('Service account key');
  } else {
    warn('service-account-key.json not found in installer');
    warn('You will need to manually place serviceAccountKey.json in ~/.claude/hooks/');
  }

  // ── Step 5: Create .env ───────────────────────────────────────────────────
  step('Configuring');

  const envContent = [
    '# Claude Notify — auto-generated by installer',
    `FIREBASE_SERVICE_ACCOUNT_PATH=${SERVICE_ACCOUNT_DEST}`,
    `FIREBASE_PROJECT_ID=${PROJECT_ID}`,
    `CLAUDE_USER_UID=${uid}`,
    '',
  ].join('\n');

  fs.writeFileSync(ENV_PATH, envContent);
  ok('.env created');

  // ── Step 6: Install npm dependencies ──────────────────────────────────────
  step('Installing dependencies');

  // Create a minimal package.json in hooks dir for deps
  const hooksPkg = {
    name: 'claude-notify-hooks',
    private: true,
    dependencies: {
      'firebase-admin': '^13.0.0',
      'dotenv': '^16.4.0',
    },
  };
  fs.writeFileSync(
    path.join(HOOKS_DIR, 'package.json'),
    JSON.stringify(hooksPkg, null, 2)
  );

  try {
    execSync('npm install --production', {
      cwd: HOOKS_DIR,
      stdio: 'pipe',
    });
    ok('firebase-admin + dotenv installed');
  } catch (e) {
    err('npm install failed. Run manually: cd ~/.claude/hooks && npm install');
  }

  // ── Step 7: Update Claude settings.json ───────────────────────────────────
  step('Updating Claude Code settings');

  let settings = {};
  if (fs.existsSync(SETTINGS_PATH)) {
    try {
      settings = JSON.parse(fs.readFileSync(SETTINGS_PATH, 'utf8'));
    } catch {
      warn('Could not parse existing settings.json, creating new one');
    }
  }

  // Determine command prefix based on OS
  const nodeCmd = 'node';
  const hooksPath = process.platform === 'win32'
    ? HOOKS_DIR.replace(/\\/g, '/')
    : '~/.claude/hooks';

  const hookConfig = {
    Stop: [
      {
        hooks: [
          { type: 'command', command: `${nodeCmd} ${hooksPath}/stop.js` },
        ],
      },
    ],
    PreToolUse: [
      {
        matcher: 'Bash',
        hooks: [
          { type: 'command', command: `${nodeCmd} ${hooksPath}/pre-tool-use.js` },
        ],
      },
    ],
    PostToolUse: [
      {
        hooks: [
          { type: 'command', command: `${nodeCmd} ${hooksPath}/post-tool-use.js` },
        ],
      },
    ],
    Notification: [
      {
        hooks: [
          { type: 'command', command: `${nodeCmd} ${hooksPath}/notification.js` },
        ],
      },
    ],
  };

  settings.hooks = { ...(settings.hooks || {}), ...hookConfig };

  // Ensure permissions allow Bash
  if (!settings.permissions) {
    settings.permissions = {};
  }

  fs.writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2));
  ok('settings.json updated with hooks');

  // ── Done ──────────────────────────────────────────────────────────────────
  log('');
  log(`${c.green}${c.bold}  ✅ Claude Notify installed successfully!${c.reset}`);
  log('');
  log(`${c.dim}  What happens now:${c.reset}`);
  log(`  ${c.bold}•${c.reset} Task finish → push notification to your phone`);
  log(`  ${c.bold}•${c.reset} Destructive commands → approval request on phone`);
  log(`  ${c.bold}•${c.reset} Activity tracking → live feed in the app`);
  log(`  ${c.bold}•${c.reset} Set "Away from desk" in the app to enable notifications`);
  log('');
  log(`${c.dim}  Hooks installed at: ${HOOKS_DIR}${c.reset}`);
  log(`${c.dim}  Settings updated at: ${SETTINGS_PATH}${c.reset}`);
  log('');
}

main().catch((e) => {
  err(e.message);
  process.exit(1);
});
